apiVersion: apps/v1
kind: Deployment
metadata:
  name: attacker
  namespace: demo
  labels:
    app: attacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attacker
  template:
    metadata:
      labels:
        app: attacker
    spec:
      containers:
      - name: attacker
        image: public.ecr.aws/k1q0d6m0/attacker
---